<a href="https://colab.research.google.com/github/mayurgurav-45/PYTHON-WORKSHOP/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Numpy**

In [3]:
import numpy as np

**Creating Numpy array**

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1,2],[3,4]],
 [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
d = ([[[[1,2],[3,4]]],[[[5,6],[7,8]]],[[[9,10],[11,12]]]])
d

[[[[1, 2], [3, 4]]], [[[5, 6], [7, 8]]], [[[9, 10], [11, 12]]]]

Data Type

In [8]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
a = np.array([1, 2, 3], dtype=np.uint8)
print(a)
print(a.dtype)

b = np.array([1, 2, 3], dtype=complex)
print(b)
print(b.dtype)


[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


Arange(start,stop,step)

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

With Reshape(depth,row,column)

In [11]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

Ones

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Zeros

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Identity

In [16]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random

In [17]:
np.random.random((3,4))

array([[0.66049417, 0.51430761, 0.32249852, 0.45861606],
       [0.20457954, 0.77027826, 0.21273174, 0.36652848],
       [0.85494172, 0.74703837, 0.43020045, 0.54339577]])

Linspace(start,end,number_between_them,data_type)

In [18]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

Randint(low,high,size)

In [19]:
np.random.randint(2,10,5)

array([4, 5, 5, 8, 3])

**Array Attributes**

ndim

In [20]:
a = np.array([1,2,3,4])
a.ndim

1

shape

In [21]:
a = np.array([1,2,3,4])
a.shape

(4,)

size

In [22]:
a = np.array([1,2,3,4])
a.size

4

dtype

In [23]:
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

itemsize

In [24]:
a = np.array([1,2,3,4])
a.itemsize

8

nbytes

In [25]:
a = np.array([1,2,3,4])
a.nbytes

32

1D Array Attributes

In [26]:
a = np.array([1,2,3,4])
print(a.ndim,a.shape,a.size,a.dtype,a.itemsize,a.nbytes)

1 (4,) 4 int64 8 32


2D Array Attributes



In [27]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim,b.shape,b.size,b.dtype,b.itemsize,b.nbytes)

2 (2, 3) 6 int64 8 48


3D Array Attributes

In [28]:
c = np.array([[[1,2],[3,4]],
 [[5,6],[7,8]]])
print(c.ndim,c.shape,c.size,c.dtype,c.itemsize,c.nbytes)

3 (2, 2, 2) 8 int64 8 64


astype

In [29]:
a.dtype

dtype('int64')

In [30]:
a.astype(np.float64).dtype

dtype('float64')

In [31]:
a.astype(np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

**Array Operations**

scalar op.

In [32]:
t = np.array([[1,2],[3,4]])
t**2

array([[ 1,  4],
       [ 9, 16]])

In [33]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8]])
t1**t2

array([[    1,    64],
       [ 2187, 65536]])

Relational

In [36]:
t2 == 6

array([[False,  True],
       [False, False]])

**Array Functions**

Round

In [34]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[98., 26., 85.],
       [29., 12., 42.],
       [71., 87., 61.]])

Max

In [43]:
np.max(a,axis=0)

array([98., 87., 85.])

Min

In [44]:
np.min(a,axis=0)

array([29., 12., 42.])

Sum

In [45]:
np.sum(a,axis=0)

array([198., 125., 188.])

Prod

In [46]:
np.prod(a,axis=0)

array([201782.,  27144., 217770.])

Mean

In [47]:
np.mean(a,axis=0)

array([66.        , 41.66666667, 62.66666667])

Median

In [48]:
np.median(a,axis=0)

array([71., 26., 61.])

Std

In [49]:
np.std(a,axis=0)

array([28.39013913, 32.56105376, 17.59419096])

Var

In [50]:
np.var(a,axis=0)

array([ 806.        , 1060.22222222,  309.55555556])

Trigonometry Funn.

In [51]:
np.sin(a)

array([[-0.57338187,  0.76255845, -0.17607562],
       [-0.66363388, -0.53657292, -0.91652155],
       [ 0.95105465, -0.82181784, -0.96611777]])

Angle array in degrees

In [52]:
deg = np.array([0,30,45,60,90])
rad = np.deg2rad(deg)
print("Angles in degrees:", deg)
print("Angles in radians:", rad)

print("Sine:", np.sin(rad))
print("Cosine:", np.cos(rad))
print("Tangent:", np.tan(rad))

Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
