<a href="https://colab.research.google.com/github/mayurgurav-45/PYTHON-WORKSHOP/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Numpy**

In [1]:
import numpy as np

**Creating Numpy array**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],
 [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
d = ([[[[1,2],[3,4]]],[[[5,6],[7,8]]],[[[9,10],[11,12]]]])
d

[[[[1, 2], [3, 4]]], [[[5, 6], [7, 8]]], [[[9, 10], [11, 12]]]]

Data Type

In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
a = np.array([1, 2, 3], dtype=np.uint8)
print(a)
print(a.dtype)

b = np.array([1, 2, 3], dtype=complex)
print(b)
print(b.dtype)


[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


Arange(start,stop,step)

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

With Reshape(depth,row,column)

In [9]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

Ones

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Zeros

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Identity

In [14]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random

In [15]:
np.random.random((3,4))

array([[0.89549619, 0.40656915, 0.54498598, 0.17168775],
       [0.36289316, 0.51813755, 0.96403443, 0.63166354],
       [0.05032909, 0.98434211, 0.53689106, 0.34484842]])

Linspace(start,end,number_between_them,data_type)

In [16]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

Randint(low,high,size)

In [17]:
np.random.randint(2,10,5)

array([4, 6, 2, 4, 7])

**Array Attributes**

ndim

In [18]:
a = np.array([1,2,3,4])
a.ndim

1

shape

In [19]:
a = np.array([1,2,3,4])
a.shape

(4,)

size

In [20]:
a = np.array([1,2,3,4])
a.size

4

dtype

In [21]:
a = np.array([1,2,3,4])
a.dtype

dtype('int64')

itemsize

In [22]:
a = np.array([1,2,3,4])
a.itemsize

8

nbytes

In [23]:
a = np.array([1,2,3,4])
a.nbytes

32

1D Array Attributes

In [24]:
a = np.array([1,2,3,4])
print(a.ndim,a.shape,a.size,a.dtype,a.itemsize,a.nbytes)

1 (4,) 4 int64 8 32


2D Array Attributes



In [25]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim,b.shape,b.size,b.dtype,b.itemsize,b.nbytes)

2 (2, 3) 6 int64 8 48


3D Array Attributes

In [26]:
c = np.array([[[1,2],[3,4]],
 [[5,6],[7,8]]])
print(c.ndim,c.shape,c.size,c.dtype,c.itemsize,c.nbytes)

3 (2, 2, 2) 8 int64 8 64


astype

In [27]:
a.dtype

dtype('int64')

In [28]:
a.astype(np.float64).dtype

dtype('float64')

In [29]:
a.astype(np.complex64)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

**Array Operations**

scalar op.

In [30]:
t = np.array([[1,2],[3,4]])
t**2

array([[ 1,  4],
       [ 9, 16]])

In [31]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8]])
t1**t2

array([[    1,    64],
       [ 2187, 65536]])

Relational

In [32]:
t2 == 6

array([[False,  True],
       [False, False]])

**Array Functions**

Round

In [33]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[18., 31., 44.],
       [89., 42., 14.],
       [85., 62., 91.]])

Max

In [34]:
np.max(a,axis=0)

array([89., 62., 91.])

Min

In [35]:
np.min(a,axis=0)

array([18., 31., 14.])

Sum

In [36]:
np.sum(a,axis=0)

array([192., 135., 149.])

Prod

In [37]:
np.prod(a,axis=0)

array([136170.,  80724.,  56056.])

Mean

In [38]:
np.mean(a,axis=0)

array([64.        , 45.        , 49.66666667])

Median

In [39]:
np.median(a,axis=0)

array([85., 42., 44.])

Std

In [40]:
np.std(a,axis=0)

array([32.56787783, 12.83225104, 31.68946548])

Var

In [41]:
np.var(a,axis=0)

array([1060.66666667,  164.66666667, 1004.22222222])

Trigonometry Funn.

In [42]:
np.sin(a)

array([[-0.75098725, -0.40403765,  0.01770193],
       [ 0.86006941, -0.91652155,  0.99060736],
       [-0.17607562, -0.7391807 ,  0.10598751]])

Angle array in degrees

In [43]:
deg = np.array([0,30,45,60,90])
rad = np.deg2rad(deg)
print("Angles in degrees:", deg)
print("Angles in radians:", rad)

print("Sine:", np.sin(rad))
print("Cosine:", np.cos(rad))
print("Tangent:", np.tan(rad))

Angles in degrees: [ 0 30 45 60 90]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Dot

In [44]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)
np.dot(a,b)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

Log

In [45]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

Expo.

In [46]:
np.log(a)

<ipython-input-46-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

Floor

In [47]:
np.floor(np.random.random((2,3))*100)

array([[ 1., 70., 47.],
       [19., 89., 55.]])

Ceil

In [48]:
np.ceil(np.random.random((2,3))*100)

array([[39., 16., 79.],
       [73., 92., 11.]])

**Iterating**

In [49]:
a
for i in a:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [52]:
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [53]:
b
for i in b:
  print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


nditer

In [54]:
for i in np.nditer(b):
  print(i)

12
13
14
15
16
17
18
19
20
21
22
23


transpose

In [55]:
np.transpose(b)
b.T

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

ravel

In [56]:
b.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

**Indexing and Slicing**

In [57]:
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [58]:
b[1,0]

np.int64(15)

In [59]:
b[1,1]

np.int64(16)

In [60]:
b[2:5:2]

array([[18, 19, 20]])

In [61]:
b[0:2,1::2]

array([[13],
       [16]])

In [62]:
b[::2,1::2]

array([[13],
       [19]])

In [63]:
b[1,::3]

array([15])

In [64]:
b[0,:]

array([12, 13, 14])

In [65]:
b[:,2]

array([14, 17, 20, 23])

In [66]:
b[1:,1:3]

array([[16, 17],
       [19, 20],
       [22, 23]])

In [68]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
c[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [70]:
c[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [71]:
c[0,1,:]

array([3, 4, 5])

In [72]:
c[::,:2:3,1::2]

array([[[ 1]],

       [[10]],

       [[19]]])